openapi: 3.0.0
info:
  title: Account API
  description: API for managing account objects
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://sandbox.api.example.com/v1
    description: Sandbox server
paths:
  /accounts:
    get:
      summary: List all accounts
      description: Retrieve a list of all accounts.
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '500':
          description: Internal server error
    post:
      summary: Create a new account
      description: Create a new account with the provided information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
  /accounts/{accountId}:
    get:
      summary: Retrieve an account
      description: Get details of a specific account by ID.
      parameters:
        - name: accountId
          in: path
          required: true
          description: The ID of the account to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found
    put:
      summary: Update an account
      description: Update details of an existing account.
      parameters:
        - name: accountId
          in: path
          required: true
          description: The ID of the account to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
        '404':
          description: Account not found
    delete:
      summary: Delete an account
      description: Delete an account by ID.
      parameters:
        - name: accountId
          in: path
          required: true
          description: The ID of the account to delete
          schema:
            type: string
      responses:
        '204':
          description: Account deleted successfully
        '404':
          description: Account not found
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the account
        name:
          type: string
          description: Name of the account
        email:
          type: string
          description: Email associated with the account
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the account was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the account was last updated
      required:
        - id
        - name
        - email
